name = "roshanfekran-academy-control-center"
main = "src/index.js"
compatibility_date = "2026-09-01"

[vars]
ENVIRONMENT = "development"
ADMIN_EMAILS = ""

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "roshanfekran-academy"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
