-- Academy Control Center v5 operational + reporting migration
create table if not exists public.academy_followups (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.academy_students(id) on delete cascade,
  due_at timestamptz not null,
  type text not null check (type in ('call','message','documents','payment','class','certificate','other')),
  status text not null default 'open' check (status in ('open','done','cancelled')),
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  assigned_to uuid references auth.users(id) on delete set null,
  note text,
  completed_at timestamptz,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.academy_expenses (
  id uuid primary key default gen_random_uuid(),
  expense_no bigint generated by default as identity unique,
  category text not null,
  title text not null,
  amount bigint not null check (amount > 0),
  expense_date date not null default current_date,
  method text not null default 'other' check (method in ('cash','card_transfer','bank_transfer','pos','other')),
  reference_no text,
  note text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.academy_teacher_payouts (
  id uuid primary key default gen_random_uuid(),
  payout_no bigint generated by default as identity unique,
  teacher_name text not null,
  course_id uuid references public.academy_courses(id) on delete set null,
  amount bigint not null check (amount > 0),
  period_label text,
  paid_at timestamptz not null default now(),
  method text not null default 'bank_transfer' check (method in ('cash','card_transfer','bank_transfer','other')),
  reference_no text,
  note text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists academy_followups_student_idx on public.academy_followups(student_id);
create index if not exists academy_followups_due_idx on public.academy_followups(status,due_at);
create index if not exists academy_followups_assigned_idx on public.academy_followups(assigned_to);
create index if not exists academy_expenses_date_idx on public.academy_expenses(expense_date);
create index if not exists academy_teacher_payouts_course_idx on public.academy_teacher_payouts(course_id);
create index if not exists academy_teacher_payouts_paid_idx on public.academy_teacher_payouts(paid_at);
create index if not exists academy_attendance_student_idx on public.academy_attendance(student_id);
create index if not exists academy_attendance_marked_by_idx on public.academy_attendance(marked_by);
create index if not exists academy_audit_actor_idx on public.academy_audit_log(actor_id);
create index if not exists academy_courses_department_idx on public.academy_courses(department_id);
create index if not exists academy_enrollments_created_by_idx on public.academy_enrollments(created_by);
create index if not exists academy_payments_created_by_idx on public.academy_payments(created_by);
create index if not exists academy_payments_installment_idx on public.academy_payments(installment_id);
create index if not exists academy_students_created_by_idx on public.academy_students(created_by);

alter table public.academy_followups enable row level security;
alter table public.academy_expenses enable row level security;
alter table public.academy_teacher_payouts enable row level security;

drop policy if exists academy_followups_staff on public.academy_followups;
create policy academy_followups_staff on public.academy_followups for all to authenticated using (public.academy_is_staff()) with check (public.academy_is_staff());

drop policy if exists academy_expenses_read on public.academy_expenses;
create policy academy_expenses_read on public.academy_expenses for select to authenticated using (public.academy_is_staff());
drop policy if exists academy_expenses_insert on public.academy_expenses;
create policy academy_expenses_insert on public.academy_expenses for insert to authenticated with check (public.academy_is_staff());
drop policy if exists academy_expenses_update on public.academy_expenses;
create policy academy_expenses_update on public.academy_expenses for update to authenticated using (public.academy_is_staff()) with check (public.academy_is_staff());

drop policy if exists academy_teacher_payouts_read on public.academy_teacher_payouts;
create policy academy_teacher_payouts_read on public.academy_teacher_payouts for select to authenticated using (public.academy_is_staff());
drop policy if exists academy_teacher_payouts_insert on public.academy_teacher_payouts;
create policy academy_teacher_payouts_insert on public.academy_teacher_payouts for insert to authenticated with check (public.academy_is_staff());
drop policy if exists academy_teacher_payouts_update on public.academy_teacher_payouts;
create policy academy_teacher_payouts_update on public.academy_teacher_payouts for update to authenticated using (public.academy_is_staff()) with check (public.academy_is_staff());

drop trigger if exists academy_followups_updated_at on public.academy_followups;
create trigger academy_followups_updated_at before update on public.academy_followups for each row execute function public.academy_set_updated_at();

create or replace view public.academy_overdue_installments with (security_invoker=true) as
select i.id, i.enrollment_id, i.installment_no, i.amount, i.paid_amount,
       (i.amount-i.paid_amount)::bigint as remaining_amount, i.due_date, i.status,
       s.id as student_id, s.student_no, s.full_name, s.mobile,
       c.id as course_id, c.title as course_title
from public.academy_installments i
join public.academy_enrollments e on e.id=i.enrollment_id
join public.academy_students s on s.id=e.student_id
join public.academy_courses c on c.id=e.course_id
where i.status in ('open','partial') and i.due_date < current_date;

create or replace view public.academy_course_finance with (security_invoker=true) as
select c.id as course_id, c.title as course_title,
       count(e.id)::int as enrollment_count,
       coalesce(sum(e.final_fee),0)::bigint as billed_total,
       coalesce(sum(f.paid_total),0)::bigint as paid_total,
       coalesce(sum(f.balance),0)::bigint as balance_total,
       case when coalesce(sum(e.final_fee),0)=0 then 0
            else round((coalesce(sum(f.paid_total),0)::numeric / sum(e.final_fee)::numeric)*100,1) end as collection_rate
from public.academy_courses c
left join public.academy_enrollments e on e.course_id=c.id and e.status in ('active','completed')
left join public.academy_enrollment_finance f on f.enrollment_id=e.id
group by c.id,c.title;

create or replace view public.academy_dashboard_summary with (security_invoker=true) as
select
  (select count(*)::int from public.academy_students where status='active') as active_students,
  (select count(*)::int from public.academy_courses where status='active') as active_courses,
  (select coalesce(sum(amount),0)::bigint from public.academy_payments) as collected_total,
  (select coalesce(sum(balance),0)::bigint from public.academy_enrollment_finance where balance>0) as receivables_total,
  (select count(*)::int from public.academy_overdue_installments) as overdue_installments,
  (select count(*)::int from public.academy_followups where status='open' and due_at <= now()+interval '24 hours') as due_followups,
  (select coalesce(sum(amount),0)::bigint from public.academy_payments where paid_at >= date_trunc('month',now())) as collected_this_month,
  (select coalesce(sum(amount),0)::bigint from public.academy_expenses where expense_date >= date_trunc('month',now())::date) as expenses_this_month,
  (select coalesce(sum(amount),0)::bigint from public.academy_teacher_payouts where paid_at >= date_trunc('month',now())) as teacher_payouts_this_month;

grant select on public.academy_overdue_installments, public.academy_course_finance, public.academy_dashboard_summary to authenticated;
